version: "3.8"

services:
  redis:
    container_name: "redis"
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=123456
      - REDIS_PORT_NUMBER=6379
    command: /opt/bitnami/scripts/redis/run.sh
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  postgres:
    image: postgres
    container_name: messengers
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: messengers
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
